spring:
  datasource:
    url: jdbc:h2:mem:./db/shareit;
    driverClassName: org.h2.Driver
    username: dbuser
    password: 12345

jpa:
  show-sql: true
  properties:
    hibernate.format_sql: true

logging.level:
  org.springframework:
    orm.jpa: INFO
    transaction: INFO
    transaction.interceptor: INFO
    orm.jpa.JpaTransactionManager: DEBUG
  org.zalando.logbook: TRACE
  ru.practicum.stats-server: DEBUG

