server.port: 9090

spring:
  sql.init.mode: always
  output.ansi.enabled: ALWAYS

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/statsdb
    username: dbuser
    password: 12345

logging.level:
  org.zalando.logbook: TRACE
  ru.practicum.stats-server: INFO